### PR TITLE
Adding flask-rest-template

### PR DESCRIPTION
**Pull request by alexandre**

### CODE REVIEW

**Comment by humiaozuzu** [comment]
Some questions:
1. do the repo has something to do with restful?
2. why no python 2.7 support

**Comment by alexandre** [comment]
@humiaozuzu ,

1=> I tried to follow a "almost" rest idea, creating a valid structure to a "rest API" (I added an example/crud, as described in the README.md). Do you think is it useful for this goal?

2 => I do not use Python 2.7 in my projects because I want to help only python3, IMO, it (python3) is the future. But feel free to send a PR with python 2.7 support...it should not be hard.

[ ]'s (hugs)

**Comment by humiaozuzu** [comment]
@alexandre sorry for the late reply.

Can you please fix the conflict and I'll merge it then.

**Comment by alexandre** [comment]
done

**Pull request merged**
