### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mjhea0**

### CODE REVIEW

**Comment by mjhea0** [comment]
Any reason why these didn't get merged?

**Comment by humiaozuzu** [comment]
Please remove line of Book Real Python for it has nothing to do with Flask.
And after merging so many pull requests, Github can not do auto merging now. And I tried rebase by my self and everything in a mess :(
Can you open another pull request with new changes?

**Comment by mjhea0** [comment]
@humiaozuzu half of the Real Python course is dedicated to Flask. We also do a ton of Flask posts on our [blog](https://realpython.com/blog/categories/flask/). Are you sure this can't be added?

Happy to open a new PR. Thanks!

**Comment by humiaozuzu** [comment]
Sorry, I didn't look into it. The book is good for Flask learners :+1:

**Comment by mjhea0** [comment]
Thanks! New PR: https://github.com/humiaozuzu/awesome-flask/pull/23

**Pull request closed without merging**
